server:
  port: 8082

# files:
#   folder: /tmp/filestore

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql1.cziyl6rwn9rl.ap-northeast-2.rds.amazonaws.com/EPRO4
    username: postgres
    password: 1q2w3e4r
    # Connection Pool
    hikari:
      pool-name: "hikari-pool"
      # pool에서 커넥션을 얻어오기전까지 기다리는 최대 시간
      connection-timeout: 28000
      # pool에 유지시킬 수 있는 최대 커넥션 수
      maximum-pool-size: 10
      # 아무런 일을 하지않아도 적어도 이 옵션에 설정 값 size로 커넥션 유지 개수
      # minimum-idle: 5
      # pool에 일을 안하는 커넥션을 유지하는 시간
      # -  minimum-idle이 maximum-pool-size보다 작게 설정되어 있을 때만 설정
      # idle-timeout: 60000

  # File Upload - 맞는 방법인지 다시 확인하기
  servlet:
    multipart:
      maxFileSize: 70000000
      maxRequestSize: 70000000
      max-file-size: 20MB  #최대 파일 사이즈를 20MB로 지정

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        # ddl_auto: update
      